// Mocks generated by Mockito 5.4.4 from annotations
// in infinity_albums/test/blocs/album_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:infinity_albums/data/models/album.dart' as _i5;
import 'package:infinity_albums/data/models/photo.dart' as _i6;
import 'package:infinity_albums/data/respositories/album_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AlbumRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlbumRepository extends _i1.Mock implements _i2.AlbumRepository {
  MockAlbumRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i4.Future<List<_i5.Album>> getAlbums() => (super.noSuchMethod(
        Invocation.method(
          #getAlbums,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Album>>.value(<_i5.Album>[]),
      ) as _i4.Future<List<_i5.Album>>);

  @override
  _i4.Future<List<_i6.Photo>> getPhotosForAlbum(int? albumId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPhotosForAlbum,
          [albumId],
        ),
        returnValue: _i4.Future<List<_i6.Photo>>.value(<_i6.Photo>[]),
      ) as _i4.Future<List<_i6.Photo>>);
}
